branches:
  only:
    - master

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

os: Windows Server 2012

build_script:
  - gradlew.bat assemble --info --no-daemon

before_test:
  - cd C:\projects\clarifai-java
  - for /f %%i in ('C:\Python36\python.exe scripts\app_and_key_for_tests.py --create-app java-appveyor') do set CLARIFAI_APP_ID=%%i
  - for /f %%i in ('C:\Python36\python.exe scripts\app_and_key_for_tests.py --create-key %CLARIFAI_APP_ID%') do set CLARIFAI_API_KEY=%%i
  - for /f %%i in ('C:\Python36\python.exe scripts\app_and_key_for_tests.py --create-workflow %CLARIFAI_API_KEY%') do rem

test_script:
  - gradlew.bat check --info --no-daemon

after_test:
  - cd C:\projects\clarifai-java
  - 'C:\Python36\python.exe scripts\app_and_key_for_tests.py --delete-app %CLARIFAI_APP_ID%'

cache:
  - C:\Users\appveyor\.gradle

matrix:
  fast_finish: true
