branches:
  only:
    - master

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

os: Windows Server 2012
build_script:
  - gradlew.bat assemble --info --no-daemon
test_script:
  - gradlew.bat check --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle

matrix:
  fast_finish: true
